export type Force3DStylePreset = {
  name: string;
  backgroundColor: string;
  labelColor: string;
  labelSize: number;
  labelBackground: string;
  labelMaxDistance: number;
  labelFontSize: number;
  labelFontSizeMax: number;
  labelStrokeWidth: number;
  labelStrokeColor: string;
  edgeBaseColor: string;
  nodeColorSaturationBoost: number;
  nodeColorLightnessBoost: number;
  edgeColorSaturationBoost: number;
  edgeColorLightnessBoost: number;
  nodeOpacity: number;
  nodeRelSize: number;
  nodeScale: number;
  nodeResolution: number;
  linkOpacity: number;
  linkWidth: number;
  linkResolution: number;
  linkDistance: number;
  arrowLength: number;
  arrowRelPos: number;
  arrowResolution: number;
  chargeStrength: number;
  controlType: 'trackball' | 'orbit' | 'fly';
  minDistance: number;
  maxDistance: number;
  focusDistance: number;
  fitPadding: number;
  fitTightness: number;
  particleWidth: number;
  particleSpeed: number;
  maxPixelRatio: number;
  bloomStrength: number;
  bloomRadius: number;
  bloomThreshold: number;
  toneMappingExposure: number;
  fogNear: number;
  fogFar: number;
  starfieldEnabled: boolean;
  starfieldCount: number;
  starfieldRadius: number;
  starfieldSize: number;
  starfieldOpacity: number;
  starfieldColor: string;
};

export const FORCE3D_PRESETS: Record<string, Force3DStylePreset> = {
  kgCosmic: {
    name: 'kgCosmic',
    backgroundColor: '#0b1020',
    labelColor: '#e2e8f0',
    labelSize: 8,
    labelBackground: 'rgba(15, 23, 42, 0.72)',
    labelMaxDistance: 520,
    labelFontSize: 160,
    labelFontSizeMax: 300,
    labelStrokeWidth: 0.1,
    labelStrokeColor: 'rgba(15, 23, 42, 0.7)',
    edgeBaseColor: 'rgba(148, 163, 184, 0.35)',
    nodeColorSaturationBoost: 0.36,
    nodeColorLightnessBoost: 0.12,
    edgeColorSaturationBoost: 0.2,
    edgeColorLightnessBoost: 0.08,
    nodeOpacity: 0.95,
    nodeRelSize: 4.6,
    nodeScale: 1.8,
    nodeResolution: 22,
    linkOpacity: 0.5,
    linkWidth: 1.4,
    linkResolution: 10,
    linkDistance: 130,
    arrowLength: 6,
    arrowRelPos: 0.88,
    arrowResolution: 10,
    chargeStrength: -170,
    controlType: 'orbit',
    minDistance: 80,
    maxDistance: 2200,
    focusDistance: 180,
    fitPadding: 100,
    fitTightness: 0.45,
    particleWidth: 1.8,
    particleSpeed: 0.012,
    maxPixelRatio: 2.5,
    bloomStrength: 0.18,
    bloomRadius: 0.2,
    bloomThreshold: 0.55,
    toneMappingExposure: 1.05,
    fogNear: 1200,
    fogFar: 5000,
    starfieldEnabled: true,
    starfieldCount: 900,
    starfieldRadius: 4200,
    starfieldSize: 2.2,
    starfieldOpacity: 0.5,
    starfieldColor: '#94a3b8',
  },
  kgVivid: {
    name: 'kgVivid',
    backgroundColor: '#e8edf4',
    labelColor: '#0b1220',
    labelSize: 9,
    labelBackground: 'rgba(255, 255, 255, 0.96)',
    labelMaxDistance: 900,
    labelFontSize: 180,
    labelFontSizeMax: 340,
    labelStrokeWidth: 0.14,
    labelStrokeColor: 'rgba(15, 23, 42, 0.55)',
    edgeBaseColor: 'rgba(15, 23, 42, 0.45)',
    nodeColorSaturationBoost: 0.24,
    nodeColorLightnessBoost: 0.05,
    edgeColorSaturationBoost: 0.12,
    edgeColorLightnessBoost: 0.02,
    nodeOpacity: 0.98,
    nodeRelSize: 5.2,
    nodeScale: 3,
    nodeResolution: 36,
    linkOpacity: 0.75,
    linkWidth: 2.4,
    linkResolution: 16,
    linkDistance: 120,
    arrowLength: 9,
    arrowRelPos: 0.88,
    arrowResolution: 16,
    chargeStrength: -160,
    controlType: 'orbit',
    minDistance: 80,
    maxDistance: 2000,
    focusDistance: 160,
    fitPadding: 90,
    fitTightness: 0.38,
    particleWidth: 2.6,
    particleSpeed: 0.012,
    maxPixelRatio: 3.2,
    bloomStrength: 0.02,
    bloomRadius: 0.08,
    bloomThreshold: 0.78,
    toneMappingExposure: 0.92,
    fogNear: 1800,
    fogFar: 6000,
    starfieldEnabled: false,
    starfieldCount: 0,
    starfieldRadius: 0,
    starfieldSize: 0,
    starfieldOpacity: 0,
    starfieldColor: '#94a3b8',
  },
  kgClean: {
    name: 'kgClean',
    backgroundColor: '#f4f6fb',
    labelColor: '#0f172a',
    labelSize: 9,
    labelBackground: 'rgba(255, 255, 255, 0.9)',
    labelMaxDistance: 850,
    labelFontSize: 130,
    labelFontSizeMax: 220,
    labelStrokeWidth: 0.1,
    labelStrokeColor: 'rgba(15, 23, 42, 0.4)',
    edgeBaseColor: 'rgba(15, 23, 42, 0.45)',
    nodeColorSaturationBoost: 0.22,
    nodeColorLightnessBoost: 0.08,
    edgeColorSaturationBoost: 0.12,
    edgeColorLightnessBoost: 0.04,
    nodeOpacity: 0.96,
    nodeRelSize: 5,
    nodeScale: 2.8,
    nodeResolution: 24,
    linkOpacity: 0.78,
    linkWidth: 2.0,
    linkResolution: 12,
    linkDistance: 110,
    arrowLength: 7,
    arrowRelPos: 0.88,
    arrowResolution: 12,
    chargeStrength: -140,
    controlType: 'orbit',
    minDistance: 80,
    maxDistance: 2000,
    focusDistance: 160,
    fitPadding: 90,
    fitTightness: 0.4,
    particleWidth: 2.2,
    particleSpeed: 0.012,
    maxPixelRatio: 2.5,
    bloomStrength: 0.12,
    bloomRadius: 0.15,
    bloomThreshold: 0.5,
    toneMappingExposure: 1.12,
    fogNear: 900,
    fogFar: 2600,
    starfieldEnabled: false,
    starfieldCount: 0,
    starfieldRadius: 0,
    starfieldSize: 0,
    starfieldOpacity: 0,
    starfieldColor: '#94a3b8',
  },
};
